/// <reference types="react" />
import * as MapboxGl from 'mapbox-gl';
export declare type MapEvent = (map: MapboxGl.Map, evt: React.SyntheticEvent<any>) => void;
export interface Events {
    onStyleLoad?: MapEvent;
    onResize?: MapEvent;
    onDblClick?: MapEvent;
    onClick?: MapEvent;
    onMouseMove?: MapEvent;
    onMouseOut?: MapEvent;
    onMoveStart?: MapEvent;
    onMove?: MapEvent;
    onMoveEnd?: MapEvent;
    onMouseDown?: MapEvent;
    onMouseUp?: MapEvent;
    onDragStart?: MapEvent;
    onDragEnd?: MapEvent;
    onDrag?: MapEvent;
    onZoomStart?: MapEvent;
    onZoom?: MapEvent;
    onZoomEnd?: MapEvent;
    onPitch?: MapEvent;
    onPitchStart?: MapEvent;
    onPitchEnd?: MapEvent;
    onWebGlContextLost?: MapEvent;
    onWebGlContextRestored?: MapEvent;
    onRemove?: MapEvent;
    onContextMenu?: MapEvent;
    onRender?: MapEvent;
    onError?: MapEvent;
    onSourceData?: MapEvent;
    onDataLoading?: MapEvent;
    onStyleDataLoading?: MapEvent;
    onTouchCancel?: MapEvent;
    onData?: MapEvent;
    onSourceDataLoading?: MapEvent;
    onTouchMove?: MapEvent;
    onTouchEnd?: MapEvent;
    onTouchStart?: MapEvent;
    onStyleData?: MapEvent;
    onBoxZoomStart?: MapEvent;
    onBoxZoomEnd?: MapEvent;
    onBoxZoomCancel?: MapEvent;
    onRotateStart?: MapEvent;
    onRotate?: MapEvent;
    onRotateEnd?: MapEvent;
}
export declare type EventMapping = {
    [T in keyof Events]: string;
};
export declare const events: EventMapping;
export declare type Listeners = {
    [T in keyof Events]: (evt: React.SyntheticEvent<any>) => void;
};
export declare const listenEvents: (partialEvents: EventMapping, props: Partial<Events>, map: MapboxGl.Map) => Listeners;
export declare const updateEvents: (listeners: Listeners, nextProps: Partial<Events>, map: MapboxGl.Map) => {
    onStyleLoad?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onResize?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onDblClick?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onClick?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onMouseMove?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onMouseOut?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onMoveStart?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onMove?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onMoveEnd?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onMouseDown?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onMouseUp?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onDragStart?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onDragEnd?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onDrag?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onZoomStart?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onZoom?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onZoomEnd?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onPitch?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onPitchStart?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onPitchEnd?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onWebGlContextLost?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onWebGlContextRestored?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onRemove?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onContextMenu?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onRender?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onError?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onSourceData?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onDataLoading?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onStyleDataLoading?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onTouchCancel?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onData?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onSourceDataLoading?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onTouchMove?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onTouchEnd?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onTouchStart?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onStyleData?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onBoxZoomStart?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onBoxZoomEnd?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onBoxZoomCancel?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onRotateStart?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onRotate?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
    onRotateEnd?: ((evt: import("react").SyntheticEvent<any>) => void) | undefined;
};
